name: Build & Push to Production

on:
  push:
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: git stuff
        run: |
          git -b release-branch-$(uuidgen)
          touch new_file.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
