name: Build & Push to Production

on: workflow_dispatch

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: git stuff
        run: |
          BRANCH_NAME=release-branch-$(uuidgen)
          git branch $BRANCH_NAME
          git checkout $BRANCH_NAME
          touch new_file.txt
          echo $BRANCH_NAME > new_file.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push --set-upstream origin $BRANCH_NAME
