name: Build dummy 2

on:
  push:
    branches:
      - "main"
    paths:
      - "dummy2/**"

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reuse_me.yml
    with:
      username: "dummy2"
