name: Build dummy 1

on:
  push:
    branches:
      - "main"
    paths:
      - "dummy1/**"

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reuse_me.yml
    with:
      username: "dummy1"
